---
- name: Call a Job via API
  hosts: localhost
  connection: local

  tasks: 
 
  - name: Get Token
    uri:
      url: https://{{ TOWER_HOST }}/api/v2/tokens/
      method: POST
      user: "{{ TOWER_USERNAME }}"
      password: "{{ TOWER_PASSWORD }}"
      headers:
       content-type: application/json
      body_format: json
      body: '{ "description": "My Access Token", "application": 1, "scope": "write" }'
      force_basic_auth: yes
      validate_certs: False
      status_code: 201
    register: token
    
  - name: Set Token Var
    set_fact: mytoken={{ token.json.token }}
    
  - name: Set Token ID
    set_fact: mytokenid={{ token.json.id }}

  - name: Call Job Job via API
    uri:
      url: https://{{ TOWER_HOST }}/api/v2/job_templates/{{ TOWER_JOB_ID }}/launch/
      method: POST
      headers:
       content-type: application/json
       authorization: Bearer {{ mytoken }}
      validate_certs: False
      status_code: 201

  - name: Eliminar Token
    uri:
      url: https://{{ TOWER_HOST }}/api/v2/tokens/{{ mytokenid }}/
      method: DELETE
      headers:
       authorization: Bearer {{ mytoken }}
      validate_certs: False
      status_code: 204
