---
- name: Call a Job via API
  hosts: localhost
  connection: local

  tasks: 
  
  - name: Call Job Job via API
    uri:
      url: https://{{ tower_url }}/api/v2/job_templates/{{ tower_job_id }}/launch/
      method: POST
      headers:
       content-type: application/json
       authorization: Bearer {{ mytoken }}
      validate_certs: False
      status_code: 201
